### ISSUE TITLE
The window can be reduced so that the widgets do not fit

### ISSUE THREAD

**Issue by gavr123456789** [elfenware/obliviate#1]
![image](https://user-images.githubusercontent.com/30507409/102350440-f8c19a00-3fb5-11eb-99c7-2d27cf3495fb.png)  
![image](https://user-images.githubusercontent.com/30507409/102350449-fd864e00-3fb5-11eb-9ddd-3330a587ee13.png)
GNOME, Arch  
Also, nice app idea.

**Comment by dar5hak** [comment]
Thanks a lot! This seems to happen because I'm using a Gtk.Overlay (for the toast to work) instead of adding the grid directly onto the window. Will look into this tonight. Do you have any pointers?

**Comment by dar5hak** [comment]
Okay, I went and fixed the window size. Feel free to reopen if the issue persists or if the size looks weird.

**Comment by dar5hak** [comment]
Gah, that didn't work really.

**Comment by dar5hak** [comment]
Today I discovered `set_geometry_hints` and that did it.
