### ISSUE TITLE
No Option to Limit Characters/Symbols Used

### ISSUE THREAD

**Issue by bebeki** [elfenware/obliviate#20]
Would it be possible to insert limits into which characters or symbols Obliviate can use? An issue I've run into is that some sites, such as eBay and PayPal, don't accept a bunch of the symbols that Obliviate uses. I tried changing the cipher key, but most still result in unaccepted symbols.

One possible solution would be a setting that limits passwords to letters and numbers only. In my head, it makes sense that the password generator could replicate the same password each time when given the same set of limitations, but I have no idea what's going on in the backend.

**Comment by dar5hak** [comment]
This is something I have thought of as well, but just asking the user to tell what the password should contain has a lot of cognitive overhead. Now you have to remember what options you provided for each site: was it just letters? Was this symbol accepted? Did it require at least one symbol, but `\` wasn't allowed?

While I agree 100% with your concern, I haven't found a better way of getting around this situation. Personally, I just don't use Obliviate for such sites, and set a manual password which my browser remembers.

Keeping this open for discussion and ideas, but still sceptical about adding another input.

**Comment by mikezila** [comment]
You could perhaps have the application provide multiple passwords. One with a normal character spread and one simple that omitted symbols.

**Comment by TwentyOneSpokes** [comment]
Would it work if you added an integer to represent a boolean based on the users selection of 'Capitals', 'Special Characters' etc. This could be appended to the end of the cipherkey and could be used to amend the ALLOWED_CHARS list? I'm a complete beginner to coding so please forgive me if this is wide of the mark. Thanks for creating the app, I'm very grateful.

**Comment by dar5hak** [comment]
@mikezila I implemented this in #23. Guess that should solve this.
